namespace: node-test
streams:
  users:
    schema:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        created_at:
          type: string
      required:
        - id
        - full_name
        - created_at
