on: push
name: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
      - run: yarn install
      - run: docker-compose up -d
      - run: yarn test
